#@ load("@ytt:data", "data")
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: tap-install-secrets
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: eso/secretstore
spec:
  provider:
    vault:
      server: #@ data.values.tap_install.secrets.eso.vault.server
      path: #@ data.values.tap_install.secrets.eso.vault.path
      version: #@ data.values.tap_install.secrets.eso.vault.version
      auth:
        kubernetes:
          mountPath: #@ data.values.tap_install.secrets.eso.vault.auth.kubernetes.mountPath
          role: #@ data.values.tap_install.secrets.eso.vault.auth.kubernetes.role
          serviceAccountRef:
            name: "tap-install-vault-sa"