tap_install:
  package_repository:
    oci_repository: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages
  version:
    package_repo_bundle_tag: "1.6.1-rc.6"
    package_version: "1.6.1-rc.6"
